const IS_RESPONSE = "IS_RESPONSE";
const TRY_TODO = "TRY_TODO";
const IS_LOADING = "IS_LOADING";
const IS_ERROR = "IS_ERROR";

const SET_NEW_DATA = "SET_NEW_DATA";
const SET_UPDATE_DATA = "SET_UPDATE_DATA";

const SET_DELETE_DATA = "SET_DELETE_DATA";


export {
    IS_RESPONSE,
    IS_LOADING,
    IS_ERROR,
    TRY_TODO,
    SET_NEW_DATA,
    SET_UPDATE_DATA,
    SET_DELETE_DATA
}